### PR TITLE
Changed the display position of EmptySearchResultBody to the center vertically.

### PR DESCRIPTION
**Pull request by Yamaton0827**
## Issue
- close #ISSUE_NUMBER

## Overview (Required)
- Empty view of the search screen is not aligned center vertically.
In figma, UFO image and description is centered in whole screen (including app top bar and search filters bar).

| figma | emulated device |
|---|---|
| ||

## Links
- Related issues
  - https://github.com/DroidKaigi/conference-app-2024/issues/853

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After | After: `show layout bounds`</br>mode ON
:--: | :--: | :--:
 |  | 

## Movie (Optional)
Before | After
:--: | :--: 
<video src="" width="300" > | <video src="" width="300" >

### CODE REVIEW

**Comment by takahirom** [comment]
Thank you for this valuable contribution. I believe we need this implementation to comply with the design. The problem is that we need to modify the `globalPositioned` each time we change the structure of a composable or add a new composable. This could make our development process difficult. I'm considering whether it might be better not to proceed with this pull request. 🙇

**Comment by naoele** [comment]
@Yamaton0827 -san @takahirom -san
Sorry to butt in, but this can be fixed with a much smaller change.
Rather than changing `globalPositioned`,
It would be better to get the size of the top element and pad it accordingly.

```kotlin
    var favoriteFiltersSize by remember { mutableStateOf(0.dp) }

    Column(modifier = modifier.fillMaxSize()) {
        FavoriteFilters(
            allFilterSelected = uiState.isAllFilterSelected,
            day1FilterSelected = uiState.isDay1FilterSelected,
            day2FilterSelected = uiState.isDay2FilterSelected,
            backgroundColor = filterBackgroundColor,
            onAllFilterChipClick = onAllFilterChipClick,
            onDay1FilterChipClick = onDay1FilterChipClick,
            onDay2FilterChipClick = onDay2FilterChipClick,
            modifier = Modifier
                .fillMaxWidth()
                .background(favoriteFiltersBackgroundColor)
                .onSizeChanged { size ->
                    favoriteFiltersSize = size.height.dp
                },
        )

        when (uiState) {
            is FavoritesSheetUiState.Empty -> {
                EmptyView(
                    modifier = Modifier.wrapContentSize(Alignment.Center)
                        .padding(bottom = WindowInsets.statusBars.asPaddingValues().calculateTopPadding() + favoriteFiltersSize)
                )
            }
```

## Screenshot
It's a little bit off from Figma, but what do you think of this change?

Before | After | Figma
:--: | :--: | :--:
 |  | 


If you're OK with it, I don't mind if you commit it like this.

By the way, it would be helpful if you could run `detekt` and organize the code.

**Comment by takahirom** [comment]
Thank you. That seems better, but I think it's not very good to add processing every time a component is added. However, if we handle it as an inset, I think it's relatively acceptable.

**Comment by naoele** [comment]
Sorry, I didn't understand what you meant by treating it as an inset.
I suggested that this would be fine if no elements will be added to FavoritesScreen in the future.

**Comment by takahirom** [comment]
I think this is a somewhat difficult problem. We also have this issue, and this PR could complicate things further.
https://github.com/DroidKaigi/conference-app-2024/issues/520

**Comment by naoele** [comment]
@takahirom -san, @Yamaton0827 -san
I understand. If that's the situation, there's no need to consider my suggestion.

**Comment by Yamaton0827** [comment]
@takahirom 
Thank you for your review and consideration. The content of the discussion was a little difficult for me, so I will try to understand it from now on.

@naoele 
Thank you for the suggestion, it was helpful.

**Comment by Yamaton0827** [comment]
This pull request is closed because of a fundamental problem. Thank you for your review.

**Pull request closed without merging**
