### PR TITLE
🧹 Fixed migratable items

### PR DESCRIPTION
**Pull request by Pluu**
## Issue
- no issues

## Overview (Required)
- Fixed migratable items
- Fixed unnecessary nullable handling

## Links
- Deprecated NestedScrollSource options
   - [Fling](https://developer.android.com/reference/kotlin/androidx/compose/ui/input/nestedscroll/NestedScrollSource#Fling())
   - [Drag](https://developer.android.com/reference/kotlin/androidx/compose/ui/input/nestedscroll/NestedScrollSource#Drag())
- Deprecated LazyLayout
   - [LazyLayout](https://developer.android.com/reference/kotlin/androidx/compose/foundation/lazy/layout/package-summary#LazyLayout(androidx.compose.foundation.lazy.layout.LazyLayoutItemProvider,androidx.compose.ui.Modifier,androidx.compose.foundation.lazy.layout.LazyLayoutPrefetchState,kotlin.Function2))

### CODE REVIEW

**Review by takahirom — APPROVED** [review]
Thank you for cleaning up our app!

**Comment by takahirom** [comment]
Could you please resolve the conflict?

**Comment by Pluu** [comment]
@takahirom I resolved the conflict

**Comment by takahirom** [comment]
Thanks!

**Pull request merged**
