### PR TITLE
Changed color of BottomAppBar of TimelineItemDetailScreen

### LINKED ISSUE #575: The color of the bottom bar on the timetable detail screen differs from the Figma design
|  actual  |  expected  |
| ---- | ---- |
| スクリーンショット 2024-08-17 23 56 21 | スクリーンショット 2024-08-17 23 56 31 |

### PR DESCRIPTION
**Pull request by urotarou**
## Issue
- close #575

## Overview (Required)
- Changed color of BottomAppBar of TimelineItemDetailScreen to SurfaceContainer (#1F2020) specified in Figma

## Links
- (none)

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After
:--: | :--:
 | 

## Movie (Optional)
Before | After
:--: | :--:
<video src="" width="300" > | <video src="" width="300" >

### CODE REVIEW

**Comment by urotarou** [comment]
@takahirom 
What might I be missing to remove the 'Waiting for response or commit' label and get a code review?

**Comment by takahirom** [comment]
Sorry, It might be a mistake 🙇

**Review by takahirom — APPROVED** [review]
Looks great! Sorry for bothering you. Thank you for your contribution.

**Comment by urotarou** [comment]
Thank you for taking time out of your busy schedule to code review. 🙇

**Pull request merged**
