### PR TITLE
feature: display session message

### LINKED ISSUE #217: Display session message feature for Android app
## Overview
Implement a feature to display session information such as cancellations using the data from TimetableItem.Session.message.
image

## Links
Code: https://github.com/DroidKaigi/conference-app-2024/blob/27ea36f1ae39693bbdb51c4d90e2a126551c8fc0/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt#L91

Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI

### PR DESCRIPTION
**Pull request by kota-shiokara**
## Issue
- close #217 

## Overview (Required)
- Add a feature that display information when a value exists in TimetableItem.Session.message.

## Links
- 

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by kota-shiokara** [comment]
Since there is no "message" in the actual data, screenshots need to be done in Roborazzi where fake data can be used.
I'm not going smoothly with screenshots in Roborazzi now, so I created a PR in draft.

**Comment by takahirom** [comment]
Looks great! Please make the pr ready!

**Comment by kota-shiokara** [comment]
Sorry, the screenshot didn't work in the end.
Please check the output of GitHub Actions!

**Comment by takahirom** [comment]
Thanks! This is better than what we have!

**Review by takahirom — APPROVED** [review]

**Pull request merged**
