### PR TITLE
Fix: In TimetableItemDetailSummaryCard, Text align is misaligned

### PR DESCRIPTION
**Pull request by kosenda**
## Issue
no issue

## Overview (Required)
I'm thinking that if the description is a single line, the align should be aligned, and if it is multiple lines, it should be centered.

## Links
- [Android developers - alignByBaseline](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/RowScope#(androidx.compose.ui.Modifier).alignByBaseline())

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Language | Before | After
:--: | :--: | :--:
ja |  | 
en |  | 

## What we tried but it didn't work
- I thought it would work if I used `modifier = Modifier.alignByBaseline()` for Icon, Title, and Description, but I decided against it because the align was not centered on multiple lines.

### CODE REVIEW

**Comment by mannodermaus** [comment]
Could you try this with the largest possible font size? I worry that we run into issue #372 with this, which @Corvus400 has addressed in #374!

**Comment by kosenda** [comment]
@mannodermaus 
Thanks for letting me know!
As you said, the problem was reproduced in this PR too. Personally, I thought it would be better to close this PR after #374 was merged, and re-create new PR.

**Comment by takahirom** [comment]
> As you said, the problem was reproduced in this PR too. Personally, I thought it would be better to close this PR after https://github.com/DroidKaigi/conference-app-2024/pull/374 was merged, and re-create new PR.

Thank you for your patience. I've merged the PR. You can create a new PR or fix the conflict.

**Comment by Corvus400** [comment]
@kosenda @mannodermaus  
Sorry for the timing. 🙇

**Comment by kosenda** [comment]
I will remake it!

**Comment by kosenda** [comment]
@takahirom @mannodermaus
I looked closely and it seemed to be fixed in #374, so I'm going to stop remaking PR 🙇

**Comment by takahirom** [comment]
I'm sorry we can't merge this PR, but your work was really good! The implementation was excellent

**Pull request closed without merging**
