### PR TITLE
:wastebasket: I deleted a plugin that had no content.

### PR DESCRIPTION
**Pull request by Corvus400**
## Issue
- None.

## Overview (Required)
- While dealing with other tasks, I found that there were plugins that were not being executed, so I deleted them.

### CODE REVIEW

**Review by takahirom — APPROVED** [review]
Thanks. I sometimes use this plugin to debug the recomposition. So how about commenting out the `apply("land.sungbin.composeinvestigator")` and just removing the plugin from the `plugins {}` block?

**Comment by Corvus400** [comment]
I'll go back to the draft for today and deal with it again tomorrow. 🙏

**Comment by Corvus400** [comment]
@takahirom 
I have modified it so that only comments are added.

**Review by takahirom — APPROVED** [review]
Thanks. 🙏

**Pull request merged**
