### PR TITLE
Fix: concurrency strict warning in StaffReducer

### LINKED ISSUE #431: [iOS] Enable Swift6 language mode
# Overview

Currently, there are many Swift Concurrency warnings in your iOS app, and you will not be able to enable Swift6 language mode if things stay as they are.
Please revise your code so that you can enable Swift6 language mode.

# Details

- [ ] `Sendable` adaption 
  - When using a model defined in Kotlin Multiplatform, "Sendable" is not supported.

### PR DESCRIPTION
**Pull request by MrSmart00**
## Issue
- In progress #431

## Overview (Required)
- Patch for a concurrency warning with Swift6 in StaffReducer

### CODE REVIEW

**Review by shin-usu — APPROVED** [review]
LGTM🎉🎊

**Comment by shin-usu** [comment]
But I think issue should not be closed.
We have to fix other features, right?

**Comment by MrSmart00** [comment]
@shin-usu 
Thanks your rapid comment!

> But I think issue431 should not be closed.
> We have to fix other features, right?

Yes, this PR is proposal for concurrency support with TCA to us.
if the PR is merged, I'll fix others i think👍

**Comment by shin-usu** [comment]
I'm glad I have same opinion!
Great PR, thanks😊

**Review by charles-b-stb — APPROVED** [review]
LGTM

**Pull request merged**
