### PR TITLE
Add EventMapItemPreview

### LINKED ISSUE #294: Add Preview for EventMapItem
We would like to improve the design of EventMapItem but we can't check the screenshots for EventMapItem.

### PR DESCRIPTION
**Pull request by kseito**
## Issue
- close #294 

## Overview (Required)
- Add EventMapItemPreview
- When I checked using Roborazzi, two images were displayed. Is this ok?

## Links
Nothing.

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After
:--: | :--:
 | 

## Movie (Optional)
Nothing.

### CODE REVIEW

**Comment by takahirom** [comment]
Sorry I tried to fix the conflict by GitHub UI. But I couldn't. Could you take  a look at it?

**Comment by kseito** [comment]
got it. i will try.

**Comment by takahirom** [comment]
Thanks!

**Comment by kseito** [comment]
@takahirom I fixed it.

**Review by takahirom — APPROVED** [review]
Thank you for your contribution! I'm looking forward to your next contribution!

**Pull request merged**
