### PR TITLE
Remove "Conference" text from selected tab

### LINKED ISSUE #451: [Android] Remove "Conference" text from selected tab
Currently when the day tab is selected in timetable view the selected tab says "Conference" above the selected date. This text is unnecessary and should be removed.

Current | Should Be
:--: | :--:
スクリーンショット 2024-08-15 0 00 57 | スクリーンショット 2024-08-15 0 01 48

### PR DESCRIPTION
**Pull request by javaman97**
## Issue
- close #451 

## Overview (Required)
-  Remove "Conference" text from selected tab in TimeTable Screen as it was unnecessary and not needed.

## Screenshot (Optional if screenshot test is present or unrelated to UI)
image

### CODE REVIEW

**Comment by takahirom** [comment]
This is how it should be. Could you take a look?
https://github.com/DroidKaigi/conference-app-2024/issues/451
image

You can also refer to the Figma design.
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54849-12900&t=2LnvcZfIuJsDZ90x-0

**Comment by takahirom** [comment]
Thank you for volunteering for this important task. I appreciate it. You can step down at any time, and we'll welcome your future contributions. But if you want to challenge yourself, you can do it.

**Comment by javaman97** [comment]
> Thank you for volunteering for this important task. I appreciate it. You can step down at any time, and we'll welcome your future contributions. But if you want to challenge yourself, you can do it.

Yes, I am challenging myself and working on it. Fixing it as expected.

**Comment by javaman97** [comment]
@takahirom Now, its look fine ?
image

**Comment by takahirom** [comment]
@javaman97 I know where to fix thanks to you!
Thank you for your contribution! I'll take care of the rest of the implementation.

**Pull request merged**
