### PR TITLE
:wrench: By upgrading the version of Compose Multiplatform itself and the accompanying dependencies, we have addressed the issue of fling scrolling not working on iOS in Compose Multiplatform.

### LINKED ISSUE #937: When I run the UI of Compose Multiplatform on my iPhone, the Fling Scroll function does not work.
[This(CMP-5947)](https://youtrack.jetbrains.com/issue/CMP-5947) is probably the cause of the problem.
The problem may be solved by changing the version of composeMultiplatform to the one listed in YouTrack.
However, there is no guarantee that this will solve the problem.

### PR DESCRIPTION
**Pull request by Corvus400**
## Issue
- close #937

## Overview (Required)
- By upgrading the version of ComposeMultiplatform to 1.7.0-alpha02, fling scrolling will also work correctly in Compose Multiplatform for iOS.
- For this reason, we have increased the version of Compose Multiplatform.
- Due to a problem with CMP-6612, VRT will not function as it is.
- As a result of correspondence with takahirom, it was found that multiple responses were necessary, so we are taking action.

## Links
- https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.7.0-alpha02
- https://youtrack.jetbrains.com/issue/CMP-5947
- https://youtrack.jetbrains.com/issue/CMP-6612/Android-context-is-not-initialized-when-retrieving-resources-in-Robolectric-unit-test

## Movie (Optional)
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/488a0f55-1a08-4dcf-a509-3501e35916ab" width="300" > | <video src="https://github.com/user-attachments/assets/d7fd0675-9f9f-4ea1-ab1f-5e480c083dc4" width="300" >

### CODE REVIEW

**Comment by Corvus400** [comment]
> Task :app-android:testDevDebugUnitTest

> KaigiAppTest > runTest[KaigiApp - when app is starting - it should show timetable items] FAILED
    java.lang.IllegalStateException: Android context is not initialized. If it happens in the Preview mode then call PreviewContextConfigurationEffect() function.

What is PreviewContextConfigurationEffect...?🤔

**Comment by takahirom** [comment]
We can refer to this issue.
https://youtrack.jetbrains.com/issue/CMP-6612/Android-context-is-not-initialized-when-retrieving-resources-in-Robolectric-unit-test

**Comment by Corvus400** [comment]
@takahirom 
Thank you for teaching me! 🙇 
When I tried the following, unfortunately, it seemed that the processing would not proceed with scrolling or swipe-type methods. 😭 

```kotlin
package io.github.droidkaigi.confsched.testing

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.platform.LocalInspectionMode

@Composable
fun ProvideAndroidContextToComposeResource(content: @Composable () -> Unit) {
    CompositionLocalProvider(LocalInspectionMode provides true) {
        content()
    }
}
```

```kotlin
    fun setContent(content: @Composable () -> Unit) {
        val repositoryProvider = EntryPoints.get(
            composeTestRule.activity.application,
            RepositoryProviderEntryPoint::class.java,
        )
            .getRepositoryProvider()
        composeTestRule.setContent {
            repositoryProvider.Provide {
                ProvideAndroidContextToComposeResource {
                    content()
                }
            }
        }
    }
```

```kotlin
    override fun test(preview: ComposablePreview<JvmAnnotationInfo>) {
        captureRoboImage("${preview.methodName}.png") {
            println(preview.methodName)
            ProvideAndroidContextToComposeResource {
                preview()
            }
        }
    }
```

**Comment by takahirom** [comment]
Something like this.

```kotlin
    override fun test(preview: ComposablePreview<JvmAnnotationInfo>) {
        captureRoboImage("${preview.methodName}.png") {
            println(preview.methodName)
            ProvideAndroidContextToComposeResource()
            preview()
        }
    }
```

**Comment by Corvus400** [comment]
@takahirom 
Since you can't directly refer to the [PreviewContextConfigurationEffect](https://github.com/JetBrains/compose-multiplatform/blob/e3a78f3f90b4cb9293dfe3bc1d2e7b94ce317fdf/components/resources/library/src/androidMain/kotlin/org/jetbrains/compose/resources/AndroidContextProvider.kt#L36) from the test module, I tried writing the following code temporarily in the model module, etc., but unfortunately, it seems that the scrolling-related test methods will never end. 😭 

```kotlin
package io.github.droidkaigi.confsched.model

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.platform.LocalInspectionMode
import org.jetbrains.compose.resources.ExperimentalResourceApi
import org.jetbrains.compose.resources.PreviewContextConfigurationEffect

@OptIn(ExperimentalResourceApi::class)
@Composable
fun ProvideAndroidContextToComposeResource() {
    CompositionLocalProvider(LocalInspectionMode provides true) {
        PreviewContextConfigurationEffect()
    }
}

```

```kotlin
    fun setContent(content: @Composable () -> Unit) {
        val repositoryProvider = EntryPoints.get(
            composeTestRule.activity.application,
            RepositoryProviderEntryPoint::class.java,
        )
            .getRepositoryProvider()
        composeTestRule.setContent {
            repositoryProvider.Provide {
                ProvideAndroidContextToComposeResource()
                content()
            }
        }
    }
```

```kotlin
    override fun test(preview: ComposablePreview<JvmAnnotationInfo>) {
        captureRoboImage("${preview.methodName}.png") {
            println(preview.methodName)
            ProvideAndroidContextToComposeResource()
            preview()
        }
    }
```

**Comment by takahirom** [comment]
Thanks. Could you remove this and try again?
https://github.com/DroidKaigi/conference-app-2024/blob/main/build.gradle.kts#L30

**Comment by Corvus400** [comment]
@takahirom 
Commenting out force(“androidx.compose.foundation:foundation:1.6.8”) did not change the result.
So, I tried changing it to force(“androidx.compose.foundation:foundation:1.8.0-alpha01”), and some tests, such as AboutScreenTest, now pass. 👍 

However, it seems that the following errors are still occurring in KaigiAppTest.kt, etc. 🤔 

```
D/LifecycleMonitor: Lifecycle status change: io.github.droidkaigi.confsched.MainActivity@a3a3b34 in: CREATED
V/ActivityScenario: Update currentActivityStage to CREATED, currentActivity=io.github.droidkaigi.confsched.MainActivity@a3a3b34
D/LifecycleMonitor: Lifecycle status change: io.github.droidkaigi.confsched.MainActivity@a3a3b34 in: STARTED
V/ActivityScenario: Update currentActivityStage to STARTED, currentActivity=io.github.droidkaigi.confsched.MainActivity@a3a3b34
D/LifecycleMonitor: Lifecycle status change: io.github.droidkaigi.confsched.MainActivity@a3a3b34 in: RESUMED
V/ActivityScenario: Update currentActivityStage to RESUMED, currentActivity=io.github.droidkaigi.confsched.MainActivity@a3a3b34

Android context is not initialized. If it happens in the Preview mode then call PreviewContextConfigurationEffect() function.
java.lang.IllegalStateException: Android context is not initialized. If it happens in the Preview mode then call PreviewContextConfigurationEffect() function.
```

**Comment by takahirom** [comment]
KaigiAppTest desn't use the setContent and we can't insert the Android context. Do you have any idea to do this? We might have to have another activity to setting the context before the test.

**Comment by Corvus400** [comment]
@takahirom 
Once I had created the TestActivity, I thought I would have to keep it the same as the MainActivity's processing at all times, so I created the KaigiAppCompositionLocalProvider as follows and tried to use it in the MainActivity.
The locations are temporary.

It seems that the following issues have been addressed.
1. Test code with scrolling
2. Test code that does not use setContent
However, there seems to be a problem with the test for the profile card at the end. 🤔 

```kotlin
package io.github.droidkaigi.confsched.model

import android.os.Build
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.ProvidedValue

@Composable
inline fun KaigiAppCompositionLocalProvider(
    locals:ProvidedValue<*>,
    crossinline content: @Composable () -> Unit,
) {
    CompositionLocalProvider(
        locals,
    ) {
        if ("robolectric" == Build.FINGERPRINT) {
            ProvideAndroidContextToComposeResource()
        }
        content()
    }
}

```

```kotlin
KaigiAppCompositionLocalProvider(
                locals = LocalClock provides clockProvider.clock(),
            ) {
                repositoryProvider.Provide {
                    KaigiApp(
                        windowSize = windowSize,
                        fontFamily = fontFamily,
                        displayFeatures = displayFeatures,
                    )
                }
            }
```

```
ProfileCardScreenTest > runTest[ProfileCardScreen - when profile card is exists - it should show card screen] STARTED

ProfileCardScreenTest > runTest[ProfileCardScreen - when profile card is exists - it should show card screen] FAILED
    java.lang.IllegalArgumentException: Software rendering doesn't support drawRenderNode
        at android.graphics.Canvas.drawRenderNode(Canvas.java:2329)
        at androidx.compose.ui.graphics.layer.GraphicsLayerV29.draw(GraphicsLayerV29.android.kt:259)
        at androidx.compose.ui.graphics.layer.GraphicsLayer.draw$ui_graphics_release(AndroidGraphicsLayer.android.kt:536)
        at androidx.compose.ui.graphics.layer.LayerSnapshotV21.toBitmap(LayerSnapshot.android.kt:116)
        at androidx.compose.ui.graphics.layer.GraphicsLayer.toImageBitmap(AndroidGraphicsLayer.android.kt:827)
        at io.github.droidkaigi.confsched.profilecard.component.CaptureableCardFrontKt$BackgroundCapturableCardFront$1$1.invokeSuspend(CaptureableCardFront.kt:45)
        at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:42)
        at io.github.droidkaigi.confsched.testing.coroutines.RunTestWithLoggingKt$runTestWithLogging$1.invokeSuspend(RunTestWithLogging.kt:17)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$1.invokeSuspend(TestBuilders.kt:316)

        Caused by:
        java.lang.IllegalArgumentException: Software rendering doesn't support drawRenderNode
```

**Comment by takahirom** [comment]
Although I think there is some room for improvement in the KaigiAppCompositionLocalProvider, I believe it is good to have it in production with `isTest()`. 
Could you push the changes you have? For this `Software rendering doesn't support drawRenderNode`, `test.systemProperties["robolectric.pixelCopyRenderMode"] = "hardware"` should work.
https://github.com/DroidKaigi/conference-app-2024/blob/bab8c007930e09ec10bd62742db5a58e4b213bde/core/droidkaigiui/src/androidMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/TestEnvironment.android.kt#L5

**Comment by Corvus400** [comment]
@takahirom 
I understand. 🫡 
Let me check before I start working. 🙇 
The current testing module is only the main module, so I think it will be necessary to change to the KMP configuration in order to place the processing to be added this time.
Is it okay to make this change?
I think that it is necessary to change the testing module to a KMP configuration and add androidMain, because it is inappropriate to place the processing that has been added this time in core:model at least.

スクリーンショット 2024-09-07 15 57 45

**Comment by takahirom** [comment]
I'm fine with having `PreviewContextConfigurationEffect` in the core/droidkaigiui's main or somewhere else. 
The testing module is a bit challenging to manage since we could encounter dependencies like this: 
`feature:session(androidUnitTest sourceset)` -> `core:testing(main (android) sourceset)` -> `feature:session(androidMain and commonMain sourceSet)`. 
I think it is okay to make testing module a KMP module, but we might face potential issues with minor use cases.

**Comment by Corvus400** [comment]
@takahirom 
I see... At this point, I don't want to embed the possibility of creating a new bug that is difficult to fix, so I will not use the KMP configuration.

**Comment by Corvus400** [comment]
@takahirom 
Excuse me, let me ask a question. 🙇 

> For this Software rendering doesn't support drawRenderNode, test.systemProperties[“robolectric.pixelCopyRenderMode”] = “hardware” should work.

This part has already been set in Android/KmpRoborazziPlugin, so there should be no need to add anything in this update, right?

https://github.com/DroidKaigi/conference-app-2024/blob/bab8c007930e09ec10bd62742db5a58e4b213bde/build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/KmpRoborazziPlugin.kt#L30-L31

https://github.com/DroidKaigi/conference-app-2024/blob/bab8c007930e09ec10bd62742db5a58e4b213bde/build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/AndroidRoborazziPlugin.kt#L27

**Comment by takahirom** [comment]
Yes, I think we need to create an issue in the Robolectric repository. But for now, how about using a try-catch block for toBitmap and adding a FIXME comment?

**Comment by takahirom** [comment]
I'll merge this PR and release version 1.3 today. Thank you for addressing many kinds of issues.

**Comment by Corvus400** [comment]
Sorry for asking so many questions throughout the day.🙇‍♂️

**Pull request merged**
