### PR TITLE
add : add Medium TopBar

### LINKED ISSUE #702: Adjust the spacing between the up button and title to match the Figma design.
image
image
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54795-26746

### PR DESCRIPTION
**Pull request by choi-woo-sung**
change Topbar beacuse Staff Screen TobBar not matched

## Issue
- close #702

## Overview (Required)
-  change LargeTobBar into MediumTobBar

## Links
- https://github.com/DroidKaigi/conference-app-2024/issues/702

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After
:--: | :--:
 | 

## Movie (Optional)
Before | After
:--: | :--:
<video src="" width="300" > | <video src="" width="300" >

### CODE REVIEW

**Comment by takahirom** [comment]
Thank you for your pull request!
We have many screens like this. I'd like to maintain consistency here. It might be challenging, but could you take a look?

**Comment by choi-woo-sung** [comment]
Okay. I try it!

**Comment by takahirom** [comment]
Thanks!

**Comment by choi-woo-sung** [comment]
@takahirom 
i fix it 
image

**Comment by takahirom** [comment]
@choi-woo-sung, could you please check the failing tests? 🙏

**Comment by choi-woo-sung** [comment]
> @choi-woo-sung, 실패한 테스트를 확인해 주시겠어요? 🙏

ok sorry..

**Comment by choi-woo-sung** [comment]
i fix it !!

**Review by takahirom — APPROVED** [review]
Looks great! Thank you for your contribution!

**Pull request merged**
