### PR TITLE
:wrench: Fixed navigation to work properly on both iOS and Android.

### LINKED ISSUE #953: [iOS・Compose Multiplatform] Navigation on about isn't working as expected
# Overview

Tapping the back button on the about screen implemented by Compose Multiplatform takes us to an unexpected screen.

# Steps to reproduce

1. Open the about screen
2. Tap the "Switch Compose Multiplatform" button and switch UI
3. Tap the contributor button and open the contributor screen
4. Tap the back button

# Video

<video src="https://github.com/user-attachments/assets/38a57b0d-4b90-419b-b88a-a3c33ef1dc16" width="300" >

### PR DESCRIPTION
**Pull request by Corvus400**
## Issue
- close #953 

## Overview (Required)
- At first, it was thought that the problem could be solved by increasing the version of composeMultiplatform, as in the following commit, so the version was increased.
  - https://github.com/DroidKaigi/conference-app-2024/pull/1010/commits/c9cd6f333b285da74945a2516c7b3410fedfbc30
- However, later investigation revealed that this version did not yet contain the fix for the problem.
- At that time, it was discovered that there was a workaround, so we tried that and were able to confirm that the problem on the iOS side had been solved.

## Links
- https://github.com/DroidKaigi/conference-app-2024/discussions/882#discussioncomment-10582468
- https://github.com/JetBrains/compose-multiplatform-core/pull/1508
- https://github.com/JetBrains/compose-multiplatform-core/releases/tag/v1.7.0-beta01
- https://github.com/JetBrains/compose-multiplatform/issues/4735#issuecomment-2090235055

## Movie (Optional)
iOS Before | iOS After
:--: | :--:
<video src="https://github.com/user-attachments/assets/1c6957ef-4da7-417c-ba39-27b7397c1ef4" width="300" > | <video src="https://github.com/user-attachments/assets/cc79040d-e687-4b1c-b9e6-5093cd4f55f9" width="300" >

Android Before | Android After
:--: | :--:
<video src="https://github.com/user-attachments/assets/659f9d20-b922-47d2-9cfd-cd656eaf6393" width="300" > | <video src="https://github.com/user-attachments/assets/ed47f719-4489-4f29-8aba-750661ae29ae" width="300" >

### CODE REVIEW

**Comment by takahirom** [comment]
It seems that the change isn't released yet. 👀

**Comment by takahirom** [comment]
Now that we can access the issues, it seems there are some workaround and the workaround 2 looks easier.
https://github.com/JetBrains/compose-multiplatform/issues/4735#issuecomment-2090235055

**Comment by Corvus400** [comment]
[This commit](https://github.com/DroidKaigi/conference-app-2024/pull/1010/commits/c9cd6f333b285da74945a2516c7b3410fedfbc30) is probably unnecessary. 🤔 
Even if you revert this commit, it seems that the iOS issue has been resolved. 🥳 
I'll revert it. 🏃

**Review by takahirom — APPROVED** [review]
Thank you for trying everything we can.

**Pull request merged**
