### PR TITLE
:wrench:  Addressed the issue of crashing when opening the app on the iPhone.

### LINKED ISSUE #745: [Compose Multiplatform] Opening ProfileCardScreen with a ProfileCard saved causes the app to crash.
# Reproduction procedure

1. Launch the application on your iPhone.
2. Operate with AboutScreen to switch the app to a multi-platform view.
3. Create a ProfileCard.
4. Open ProfileCardScreen.

- If you do not make any screen transitions after creating a ProfileCard, the app will not crash even if you use ProfileCardScreen to go back and forth between the Edit/Card screens during that time.
- If you start with EditCardScreen with no ProfileCard, the app will not crash.
- This is the only line in the error log that seems relevant.

```
Uncaught Kotlin exception: kotlin.IllegalStateException: Size is unspecified
```

If a ProfileCard exists | If the ProfileCard does not exist
:--: | :--:
<video src="https://github.com/user-attachments/assets/62d09610-71eb-4a34-9228-402aba785361" width="300" > |

### PR DESCRIPTION
**Pull request by Corvus400**
## Issue
- close #745

## Overview (Required)
- There was a case where an ImageBitmap was passed to the back/frontImage of a ShareableProfileCard with a size of 0, and if this was not handled, the application would always crash.
- Therefore, we fixed it so that onCaptured is called when the Front/Back card to be captured is displayed and the size is definitely no longer 0.
- Also, the share button could be pressed at any time, but in some cases it could be pressed before the image was generated, so this has also been addressed.

## Links
- https://developer.android.com/develop/ui/compose/graphics/draw/modifiers?hl=ja#drawwithcache

## Movie (Optional)
<video src="https://github.com/user-attachments/assets/4cdb150e-aa16-43ba-81fa-9d3edfd97c23" width="300" >

### CODE REVIEW

**Comment by takahirom** [comment]
I'm not sure, but the enabled = isReadyShare isn't applied in tests. 👀 
enabled = isReadyShare

**Comment by takahirom** [comment]
I'm waiting for `linkDebugFrameworkIosArm64`

**Comment by takahirom** [comment]
Now there is no diffs. And I think I was able to open iOS's Compose Profile card
image

**Comment by Corvus400** [comment]
@takahirom 
Thank you for correcting this in your sleep! 🙇

**Pull request merged**
