### PR TITLE
Scroll to current time session when opening the timetable

### LINKED ISSUE #509: Scroll to current time session when opening the timetable
I think it would be convenient if we could see the session that's currently in progress.
If we could have a test implementation as well, it would be great.

### PR DESCRIPTION
**Pull request by yjyoon-dev**
## Issue
- close #509 

## Overview (Required)
- Modified `TimeSlot` to have an Instant value for calculating scroll position
- Implement automatic scrolling function in Timetable's list and grid views to the currently ongoing session.
- Unfortunately, despite my efforts, I was unable to implement tests for this feature. I think I'll need help from other contributors.

## Movie (Optional)
<video src="https://github.com/user-attachments/assets/a7965d0a-0bfd-4459-b857-abcd63ad3812" width="300" >

### CODE REVIEW

**Comment by takahirom** [comment]
Thank you for your pull request. Could you please check the failing tests?

**Comment by takahirom** [comment]
I was saying that I would like to have a test run too. Because if we have a crash on the day, it would be hell 😭

>If we could have a test implementation as well, it would be great.

**Comment by takahirom** [comment]
@yjyoon-dev Could you take some time to fix this?

**Comment by yjyoon-dev** [comment]
@takahirom My work has suddenly become so busy that it seems difficult to invest time. I guess I'll have to pass this issue on to someone else. I'm really sorry😭😭

**Comment by takahirom** [comment]
Thank you for your response.
I understand that work can suddenly become busy. I look forward to your next contribution!

**Pull request closed without merging**
