### PR TITLE
Profile card scrollable on small devices 

### LINKED ISSUE #703: Make the profile card scrollable
When displaying the profile card on a small device, the share button and edit button are not visible

### PR DESCRIPTION
**Pull request by yuchan2215**
## Issue
- close #703 

## Overview (Required)
- Made the profile card scrollable on small devices (when the height is low).

## Links
- 

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After
:--: | :--:
 | 

## Movie (Optional)
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/e93852c8-dada-42a9-af3f-0e79fbcfe076" width="300" > | <video src="https://github.com/user-attachments/assets/b415c3c5-1ebd-4116-8ce0-cd0fc014c49b" width="300" >

### CODE REVIEW

**Review by takahirom — APPROVED** [review]
Looks great! Thank you for your contribution!

**Comment by takahirom** [comment]
Sorry, could you please resolve the conflict?

**Comment by yuchan2215** [comment]
Resolved!

**Comment by takahirom** [comment]
Thanks!

**Pull request merged**
