### PR TITLE
fix: timetableGridItem title maxLine3 while keeping the existing layout

### LINKED ISSUE #902: TimeTableGridItem title text line count is different from Figma
## Overview

As far as Figma is concerned, it should ellipsis if the number of rows in the Title of a TimeTableGridItem is more than 3, but that does not seem to be the case in practice.

After a brief investigation, it seems that it cannot be fixed by simply modifying [the maxLines of the corresponding Text Composable](https://github.com/DroidKaigi/conference-app-2024/blob/7b153b56db624975ba19b599a52a373e4b16d255/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt#L253-L257), and that it may be necessary to adjust [the function that calculates the height of the text](https://github.com/DroidKaigi/conference-app-2024/blob/633113d4f490cc760bbe1ee962084167255ce662/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt#L333) or [the weight of the Column](https://github.com/DroidKaigi/conference-app-2024/blob/633113d4f490cc760bbe1ee962084167255ce662/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt#L154-L185).

|Figma|Actual|
|:--:|:--:|
|スクリーンショット 2024-08-31 18 15 53||

### PR DESCRIPTION
**Pull request by Matuyuhi**
## Issue
- close #902 

## Overview (Required)
- This PR fixes the timelineText component to ensure it is limited to a maximum of three lines while preserving the existing layout.

## Links
- 

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by Matuyuhi** [comment]
↑ Fix padding between texts

**Comment by takahirom** [comment]
Looks great! Could we have screenshot tests so we can check the three lines of the sessions?

**Comment by Matuyuhi** [comment]
Thanks! I'll wait for the running test as it is.

**Comment by Matuyuhi** [comment]
Added preview of long titles!

**Comment by takahirom** [comment]
I think it might be better for this pattern to be on one line because the space between the title and the speaker icon is a little narrow.
image

**Comment by Matuyuhi** [comment]
good idea. I would put the same spacing between the title and the speaker icon as the schedule.

**Comment by takahirom** [comment]
Thanks!

**Comment by Matuyuhi** [comment]
Ready to tests!

**Review by takahirom — APPROVED** [review]
Looks great! Thank you for fixing this difficult layout.

**Pull request merged**
