### PR TITLE
:sparkles: The AboutScreen header image animation ON/OFF function and the Fallback function for devices with low memory capacity have been implemented.

### PR DESCRIPTION
**Pull request by Corvus400**
## Issue
- None
- This PR will be opened after the following PRs are merged
  - #637 

## Overview (Required)
- 

## Links
- 

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After
:--: | :--:
 | 

## Movie (Optional)
Before | After
:--: | :--:
<video src="" width="300" > | <video src="" width="300" >

### CODE REVIEW

**Comment by Corvus400** [comment]
@takahirom 

This PR is designed to

1. animation ON/OFF
2. turning FallbackMode ON/OFF

I would like to close and reopen the PR since it handles both of the above at once. 🙇 

Please let me check before closing. ✋ 
I am thinking of using the contents of No. 2 of this PR to address the #650 problem.
What do you think about the above?

**Comment by Corvus400** [comment]
@takahirom 
Sorry, am I correct that [this post](https://github.com/DroidKaigi/conference-app-2024/pull/650#issuecomment-2297812665) is in response to this PR reference? 🙇 

If so, is it correct to say that both of the above two functions are unnecessary? 🙇

**Comment by takahirom** [comment]
I apologize for the unclear answer. I believe we don't have settings for animation or image display. Having these settings would be difficult for users to manage.

**Comment by Corvus400** [comment]
@takahirom 
I understand.
I will discard this implementation. 🫡 
We will implement it in a way that judges only by API Level, not by the amount of memory installed.

**Comment by takahirom** [comment]
I think the problem lies in the OS implementation of Vector Drawable.

**Comment by Corvus400** [comment]
Discard this PR to be handled by #673.

**Pull request closed without merging**
