### PR TITLE
add imePadding whether search result is empty or not

### PR DESCRIPTION
**Pull request by rand16**
## Issue
- close https://github.com/DroidKaigi/conference-app-2024/issues/519

## Overview (Required)
- The session items are hidden when the keyboard is out in SearchScreen.
- I added `imePadding` on SearchScreen wether search result is empty or not.

## Movie (search result is)
not empty | empty
:--: | :--:
<video src="https://github.com/user-attachments/assets/a86324a9-f5a0-4aff-80e1-cfe2a9d16ea2" width="300" > | <video src="https://github.com/user-attachments/assets/9de2ea95-4957-436e-a823-2926d942828e" width="300" >

### CODE REVIEW

**Comment by takahirom** [comment]
Thank you for your pull request! Could you please resolve the conflicts with the main branch?

**Comment by rand16** [comment]
> Could you please resolve the conflicts with the main branch?

I'm done!

**Review by takahirom — APPROVED** [review]
Looks great! Thank you for your contribution!

**Comment by rand16** [comment]
I'm happy to hear that!

**Pull request merged**
