### PR TITLE
[StaffScreen] center title when small state in LargeTopAppBar

### LINKED ISSUE #228: Center align title in Staff screen app bar when it's in small state
## Overview
When the app bar in the Staff screen is in its small state, the title should be center-aligned for better visual consistency and user experience.
image

## Links
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI
- Code: https://github.com/DroidKaigi/conference-app-2024/blob/77226c43d551c07bba9f35ba8becef25b2e271d3/feature/staff/src/commonMain/kotlin/io/github/droidkaigi/confsched/staff/StaffScreen.kt#L68

### PR DESCRIPTION
**Pull request by kosenda**
## Issue
- close #228 

## Overview (Required)
- Use ScrollBehavior.state.collapsedFraction so that the title is centered on the screen when the TopAppBar is collapsed.
- The `0.7f..1.0f` and `0.0f..0.5f` are set to values that looked good after trying them out.
## Things I tried that didn't work
- I thought I could set requiredWidth(screenWidth) to modifier using LocalConfiguration.screenWidth.dp in the title text, but it was not possible because the padding was a little to the right because of the size of the navigationIcon.

## Movie
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/d58d878f-9013-4b33-8ad7-7cc1008ab1b5" width="300" > | <video src="https://github.com/user-attachments/assets/76e76154-9de1-4a91-ba60-492e6bd71c0d" >

### CODE REVIEW

**Comment by takahirom** [comment]
@kosenda Are there any points to address to make this PR ready?

**Comment by kosenda** [comment]
@takahirom 
I'm trying to make the transition a little smoother 🙇
So, give me a little more time to try it!

**Comment by takahirom** [comment]
Just to let you know that you might refer to this implementation. 👀 
https://github.com/DroidKaigi/conference-app-2024/pull/293

**Comment by kosenda** [comment]
@takahirom cc: 
Sorry for the delay. I'm now ready and open!
However, It looks quite different from 293, what do you think...?

**Comment by kosenda** [comment]
The same LargeTopAppBar is expected to be used in ContributorsScreen as well, so I have moved it.

**Comment by takahirom** [comment]
@nobonobopurin 
Can I consult you about an animation? There are two implementations for centering the title. Do you have a preference for which animation you like?
https://github.com/DroidKaigi/conference-app-2024/pull/292
https://github.com/DroidKaigi/conference-app-2024/pull/293

**Comment by nobonobopurin** [comment]
@takahirom 
Thanks for reaching out. Animation #293 is closer to what I had in mind.

**Comment by takahirom** [comment]
@nobonobopurin Thank you for your opinion!

**Review by takahirom — APPROVED** [review]
Thank you for your patience and contribution!

**Pull request merged**
